apiVersion: v1
kind: Service
metadata:
  name: persistencia-service
spec:
  selector:
    app: servico-de-persistencia  
  ports:
    - name: http
      protocol: TCP
      port: 80 
      targetPort: 7002 



